---
name: version
on:
  pull_request:
    branches: ["main", "master"]
jobs:
  lint:
    uses: pokerops/ansible-utils/.github/workflows/lint.yml@master
  secrets:
    GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
