---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: {{ "${{ github.workflow }}-${{ github.ref }}" }}
  cancel-in-progress: true
jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
    steps:
      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: "make install requirements test"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_SCENARIO: {{ "${{ matrix.scenario }}" }}
