---
name: molecule
on:
  pull_request:
    branches: ["main", "master"]
    paths-ignore:
      - "galaxy.yml"
      - "**.md"
      - "**.MD"
concurrency:
  group: {{ "${{ github.workflow }}-${{ github.ref }}" }}
  cancel-in-progress: true
jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
    steps:
      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: just --set MOLECULE_SCENARIO ${{ matrix.scenario }} test
