---
name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: tcook/pokerops.actions/.github/workflows/release.yml@master
    secrets:
      GALAXY_API_KEY: ${{ "{{" }} secrets.GALAXY_API_KEY {{ "}}" }}
