---
name: devbox
description: Execute a devbox command in the specified path
inputs:
  path:
    description: "Devbox path"
    required: false
    default: "./"
  pre:
    description: "Prepare command to run"
    required: false
    default: ""
  run:
    description: "Devbox command to run"
    required: false
    default: "make test"
  checkout:
    description: "Checkout the codebase"
    required: false
    default: "true"
  install:
    description: "Install Devbox"
    required: false
    default: "true"
  cache:
    description: "Enable caching for Devbox installation"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Check out the codebase
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
      if: ${{ inputs.checkout == 'true' }}

    - name: Prepare environment
      run: ${{ inputs.pre }}
      shell: bash
      if: ${{ inputs.pre != '' }}

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.14.0
      with:
        enable-cache: ${{ inputs.cache }}
        project-path: ${{ inputs.path }}
      if: ${{ inputs.install == 'true' }}

    - name: Run devbox command
      run: devbox run -- ${{ inputs.run }}
      working-directory: ${{ inputs.path }}
      shell: bash
