---
name: build
description: Collection build workflow
on:
  workflow_call:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Build collection
        run: |
          if [ -f galaxy.yml ]; then
            devbox run build
          else
            echo "galaxy.yml not found, skipping build."
            exit 0
          fi
