---
name: actionlint
on:
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Lint action definitions
        uses: raven-actions/actionlint@v2
