---
name: build
description: Build workflow
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build collection
        uses: pokerops/ansible-utils@master
        with:
          run: make requirements build
          cache: "false"
