---
name: dependencies
on:
  pull_request:
    branches: [main, master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Install just
        run: sudo apt-get update && sudo apt-get install -y just yq

      - name: Run just check deps
        run: just check-deps
