---
name: molecule
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: molecule
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: pokerops/ansible-utils@master
        with:
          run: "make install requirements test"
