---
name: release
description: Release workflow
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
    steps:
      - name: Set up repository
        uses: pokerops/ansible-utils@master
        with:
          run: "make publish"
