---
name: release
description: Release workflow
on:
  workflow_call:
    secrets:
      GALAXY_API_KEY:
        description: "Galaxy API key"
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"
    steps:
      - name: Set up repository
        uses: pokerops/ansible-utils@master
        with:
          run: "make publish"
