---
name: version
description: Version validation and comparison workflow
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      is_pr: ${{ steps.check.outputs.is_pr }}
    steps:
      - name: Check action is running in PR context
        id: check
        run: |
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "Running in PR #${{ github.event.pull_request.number }}"
          else
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "Not running in a PR context. Skipping version check."
          fi

  version:
    runs-on: ubuntu-latest
    needs: context
    env:
      GH_TOKEN: ${{ github.token }}
    if: needs.context.outputs.is_pr == 'true'
    steps:
      - name: Run make ${{matrix.target}}
        uses: pokerops/ansible-utils@master
        with:
          run: "make version-check"
          cache: "false"
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
